// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqqj-I955yWVmXoJKEj9eD262ZmlgEGEU',
    appId: '1:653946372876:web:f1615900f6e3cdd6b3bf29',
    messagingSenderId: '653946372876',
    projectId: 'ocr-scanner-e19b4',
    authDomain: 'ocr-scanner-e19b4.firebaseapp.com',
    storageBucket: 'ocr-scanner-e19b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76__jAakQo64ft1fNA15voe5Fuk_VWC4',
    appId: '1:653946372876:android:9edd40b0fedeb82eb3bf29',
    messagingSenderId: '653946372876',
    projectId: 'ocr-scanner-e19b4',
    storageBucket: 'ocr-scanner-e19b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG_Zrgqd-CzH0PC0Sndb-Obf69TH0DcN4',
    appId: '1:653946372876:ios:4ec026217b8bc998b3bf29',
    messagingSenderId: '653946372876',
    projectId: 'ocr-scanner-e19b4',
    storageBucket: 'ocr-scanner-e19b4.appspot.com',
    iosBundleId: 'com.example.ocrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG_Zrgqd-CzH0PC0Sndb-Obf69TH0DcN4',
    appId: '1:653946372876:ios:af3b51e5c6d23afab3bf29',
    messagingSenderId: '653946372876',
    projectId: 'ocr-scanner-e19b4',
    storageBucket: 'ocr-scanner-e19b4.appspot.com',
    iosBundleId: 'com.example.ocrScanner.RunnerTests',
  );
}
